[workspace]
resolver = "2"
members = [
  "boot-efi",
]

[profile.release]
# lto = true
opt-level = "z"

[workspace.dependencies]
uefi = { version="0.30.0", features = ['global_allocator']}
uefi-raw = {version="0.6.0"}
